### ISSUE TITLE
Missing `secret_token` and `secret_key_base`

### ISSUE THREAD

**Issue by pietheinstrengholt** [scavone/feedbin-docker#1]
Hi,

Thanks for your hard work on this. I got the containers up and running, but encountering an error:

`Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml``

If you have a solution for this I would be glad to hear

**Comment by pietheinstrengholt** [comment]
I fixed the issue by adding this file: 

config/secrets.yml
# be sure to restart your server when you modify this file...
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
development:
  secret_key_base:  asdflkjasdlfkjasldfkj

test:
  secret_key_base:  asdflkhasldfhlhaskdlflakhsdf

production:
  secret_key_base: 523lk5h2lkjlj6nlk4n6lk4

Perhaps an idea to add such a file by default?

**Comment by romanar** [comment]
You mean add the `secrets.yml` 
```
development:
  secret_key_base:  asdflkjasdlfkjasldfkj
test:
  secret_key_base:  asdflkhasldfhlhaskdlflakhsdf
production:
  secret_key_base: 523lk5h2lkjlj6nlk4n6lk4
```
file in `/opt/feedbin/config` directory.
